AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

  RunRailsCops: true

# Indent private/protected/public as deep as method definitions
Style/AccessModifierIndentation:
  EnforcedStyle: outdent
  SupportedStyles:
    - outdent
    - indent

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false
