---
- name: Upload site configuration file
  sudo: yes
  template:
    src: hellolocker.com.j2
    dest: /etc/nginx/sites-available/hellolocker.com
  notify: restart nginx

- name: Enable site
  sudo: yes
  file:
    src: /etc/nginx/sites-available/hellolocker.com
    dest: /etc/nginx/sites-enabled/hellolocker.com
    state: link
  notify: restart nginx
